### ISSUE TITLE
constant "MAX_OPT+1" would not compile on Arduino IDE 2.3.2

### ISSUE THREAD

**Issue by hipe-0** [KrisKasprzak/ILI9341_t3_Menu#5]
Hello Mr Kasprzak, see title, I cannot compile any of your example file. for example ILI9341_t3_Menu_ButtonInput 

I get screenlenght of compilation error messages apparently due to one cause. A single constant mispelled apparently. 
Root cause: The "+" sign in "MAX_OPT+1" is not allowed for naming in the IDE.

example of error messages:
In file included from C:\Users\mouni\AppData\Local\Temp\.arduinoIDE-unsaved2025027-21924-1py8384.r689\ILI9341_t3_Menu_ButtonInput\ILI9341_t3_Menu_ButtonInput.ino:21:
g:\Dropbox\HIPPO'S FILES\HippoProjects\2025HippoProjects\Arduino\libraries\ILI9341_t3_Menu-main/ILI9341_t3_Menu.h:55:9: warning: ISO C++11 requires whitespace after the macro name
   55 | #define MAX_OPT+1 15                            // max elements in a menu, increase as needed
      |         ^~~~~~~
g:\Dropbox\HIPPO'S FILES\HippoProjects\2025HippoProjects\Arduino\libraries\ILI9341_t3_Menu-main/ILI9341_t3_Menu.h:55:19: error: expected ']' before numeric constant
   55 | #define MAX_OPT+1 15                            // max elements in a menu, increase as needed
      |                   ^~
g:\Dropbox\HIPPO'S FILES\HippoProjects\2025HippoProjects\Arduino\libraries\ILI9341_t3_Menu-main/ILI9341_t3_Menu.h:140:21: note: in expansion of macro 'MAX_OPT'
  140 |         float value[MAX_OPT+1];
      |                     ^~~~~~~

So I replaced in the file ILI9341_t3_Menu.h all occurence of string
old: MAX_OPT+1
new: MAX_OPT_PLUS_1

and it works

Hoping it helps. Can you reissue your library with the correction ?

I also recommend that you create "git hub releases" so that I could have used an older version of your library as I remember this was working some time ago. (a year ago maybe)

thanks

**Comment by KrisKasprzak** [comment]
search and replace broke that

should be 

#define MAX_OPT 15
